const data=[
['2026-06-22',54995.05,3858,3314,263,40,5,0,35],['2026-06-23',43396.40,3501,3004,237,39,5,0,34],['2026-06-24',43095.71,3271,2783,252,49,7,0,42],['2026-06-25',58645.31,4610,3983,370,76,6,0,70],['2026-06-26',70669.60,4917,4324,398,65,2,0,63],['2026-06-27',61892.75,4459,3885,385,79,8,0,71],['2026-06-28',68793.99,5259,4525,445,74,2,0,72],['2026-06-29',60950.79,4771,4163,411,74,8,0,66],['2026-06-30',57931.31,4387,3853,416,58,4,0,54],['2026-07-01',70136.66,4586,3963,453,76,4,0,72],['2026-07-02',60978.31,4293,3739,390,76,6,24,46],['2026-07-03',66632.90,4873,4289,490,88,7,35,46],['2026-07-04',66708.09,5599,4953,511,80,2,30,48],['2026-07-05',82984.71,6079,5419,567,106,6,35,65]
].map(([date,cost,installs,logins,trials,paid,p199,p299,p499])=>({date,cost,installs,logins,trials,paid,p199,p299,p499,loginTrial:trials/logins,trialPaid:paid/trials,loginPaid:paid/logins,cac:cost/paid}));
const $=s=>document.querySelector(s), fmt=n=>Math.round(n).toLocaleString('en-IN'), money=n=>'₹'+Math.round(n).toLocaleString('en-IN'), pct=n=>(n*100).toFixed(n<.05?2:1)+'%', paybackFmt=n=>`${(n*30).toFixed(0)} days / ${n.toFixed(2)} mo`;
const totals=()=>{const t=data.reduce((a,d)=>{for(const k of ['cost','installs','logins','trials','paid','p199','p299','p499'])a[k]+=d[k];return a},{cost:0,installs:0,logins:0,trials:0,paid:0,p199:0,p299:0,p499:0});return {...t,loginTrial:t.trials/t.logins,trialPaid:t.paid/t.trials,loginPaid:t.paid/t.logins,cac:t.cost/t.paid,date:'all'}};
const scenarioDefaults={spend:82984.71,clicks:16660,installs:6079,installTrialPct:9.33,trialPaidPct:18.69,arpu:469,llmCost:277.5,m1RetentionPct:35,m2RetentionPct:30};
const scenarioFields=[['spend','Ad spend (₹)'],['clicks','Clicks'],['installs','Installs'],['installTrialPct','Install → trial (%)'],['trialPaidPct','Trial → paid (%)'],['arpu','Monthly ARPU (₹)'],['llmCost','Blended LLM cost (₹)'],['m1RetentionPct','M1 retention (%)'],['m2RetentionPct','M2 retention (%)']];
let scenario={...scenarioDefaults,...JSON.parse(localStorage.getItem('hiastro-scenario')||'{}')};
function metric(value,label,highlight=false){return `<div class="metric ${highlight?'highlight':''}"><strong>${value}</strong><span>${label}</span></div>`}
const targetDefinitions=[
  {name:'Weekly growth',definition:'New subscriber growth week over week',current:()=>.279,target:.50,format:pct,higher:true,source:'Workbook baseline'},
  {name:'Cost per click',definition:'Ad spend divided by ad clicks',current:()=>4.98115422,target:3.831657092,format:money,higher:false,source:'Workbook baseline'},
  {name:'Cost per install',definition:'Ad spend divided by unique installs',current:d=>d.cost/d.installs,target:10.51838229,format:money,higher:false,source:'Observed cohort'},
  {name:'Install → trial',definition:'Unique trial users divided by new installs',current:d=>d.trials/d.installs,target:.13,format:pct,higher:true,source:'Observed cohort'},
  {name:'Cost per trial',definition:'Ad spend divided by unique trial users',current:d=>d.cost/d.trials,target:80.91063304,format:money,higher:false,source:'Observed cohort'},
  {name:'Trial → subscription',definition:'Trial users with a captured monthly payment',current:d=>d.trialPaid,target:.18,format:pct,higher:true,source:'Observed 7-day cohort'},
  {name:'Subscriber CAC',definition:'Ad spend divided by unique paid subscribers',current:d=>d.cac,target:449.5035169,format:money,higher:false,source:'Observed 7-day cohort'},
  {name:'CAC payback · ad only',definition:'Subscriber CAC ÷ ₹469 monthly ARPU; revenue-based, 30-day month',current:d=>d.cac/469,target:449.5035169/469,format:paybackFmt,higher:false,source:'Observed CAC + workbook ARPU'},
  {name:'CAC payback · fully loaded',definition:'(Subscriber CAC + ₹277.50 blended LLM cost) ÷ ₹469 monthly ARPU',current:d=>(d.cac+277.5)/469,target:643.7535169/469,format:paybackFmt,higher:false,source:'Observed CAC + workbook cost model'},
  {name:'Minutes per subscriber',definition:'Chat + call minutes per subscriber per week',current:()=>26.2,target:null,format:n=>n.toFixed(1),higher:true,source:'Workbook baseline'},
  {name:'M1 retained minutes',definition:'Weekly minutes among M1 retained subscribers',current:()=>null,target:null,format:n=>n,higher:true,source:'Definition required'},
  {name:'M1 engaged',definition:'Subscribers retained and engaged in month 1',current:()=>null,target:null,format:n=>n,higher:true,source:'Definition required'}
];
function renderScorecard(d){
  $('#scorecard').innerHTML=targetDefinitions.map(k=>{const c=k.current(d),has=c!=null&&k.target!=null,met=has&&(k.higher?c>=k.target:c<=k.target),state=!has?'pending':met?'on-track':'off-track',label=!has?'Pending definition':met?'Target met':'Needs improvement';const ratio=has?(k.higher?c/k.target:k.target/c):0;return `<article class="score-item"><div class="score-top"><h3>${k.name}</h3><span class="status ${state}">${label}</span></div><div class="score-values"><div><span>Current</span><strong>${c==null?'TBD':k.format(c)}</strong></div><div><span>Target</span><strong>${k.target==null?'TBD':k.format(k.target)}</strong></div></div><div class="progress"><i style="width:${Math.min(100,Math.max(0,ratio*100))}%"></i></div><p class="score-definition">${k.definition}<br><b>${k.source}</b></p></article>`}).join('');
  $('#economics').innerHTML=[
    ['LLM cost / subscriber','₹278','Target: <b>under ₹200</b> across five months'],
    ['Total cost / subscriber','₹1,035','CAC + five-month blended LLM cost; modeled target <b>₹644</b>'],
    ['Monthly ARPU','₹469','Planning goal: <b>maintain ₹469</b> per subscriber'],
    ['Retention','M1 35%','Planning targets: <b>M1 38%</b> and <b>M2 30%</b>'],
    ['Impression cost','₹0.076','Modeled target: <b>₹0.058</b>'],
    ['30-day cohort revenue','₹56,130','Workbook cumulative revenue after second payment'],
    ['60-day cohort revenue','₹72,969','Workbook cumulative revenue after third payment'],
    ['120-day cohort revenue','₹91,541','Workbook cumulative revenue after fifth payment']
  ].map(x=>`<article class="economics-card"><h3>${x[0]}</h3><strong>${x[1]}</strong><p>${x[2]}</p></article>`).join('');
}
function renderSummary(d,selected){const trialGap=d.trials/d.installs-.13,cacGap=d.cac-449.5035169,payback=d.cac/469;$('#summaryTitle').textContent=selected==='all'?'14-day operating view':new Date(d.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'long'})+' cohort';$('#summaryPoints').innerHTML=[`<div class="summary-point"><strong>${fmt(d.paid)} paid · ${money(d.cac)} CAC</strong><span>${cacGap<=0?'CAC is at or below target.':`CAC is ${money(cacGap)} above the ₹450 target.`}</span></div>`,`<div class="summary-point"><strong>${pct(d.trials/d.installs)} install → trial</strong><span>${trialGap>=0?'Target met.':`${Math.abs(trialGap*100).toFixed(1)} percentage points below the 13% target.`} Trial → paid is ${pct(d.trialPaid)}.</span></div>`,`<div class="summary-point"><strong>${paybackFmt(payback)} payback</strong><span>Ad-only, revenue-based at ₹469 monthly ARPU. Fully loaded: ${paybackFmt((d.cac+277.5)/469)}.</span></div>`].join('')}
function retainedPayback(cost,s){const month0=s.arpu,month1=s.arpu*s.m1RetentionPct/100,month2=s.arpu*s.m2RetentionPct/100;if(cost<=month0)return `${Math.ceil(cost/month0*30)} days`;if(cost<=month0+month1&&month1>0)return `${Math.ceil(30+(cost-month0)/month1*30)} days`;if(cost<=month0+month1+month2&&month2>0)return `${Math.ceil(60+(cost-month0-month1)/month2*30)} days`;return '>90 days'}
function scenarioMetrics(){const s=scenario,trials=s.installs*s.installTrialPct/100,paid=trials*s.trialPaidPct/100,cpc=s.spend/s.clicks,cpi=s.spend/s.installs,cpt=s.spend/trials,cac=s.spend/paid,total=cac+s.llmCost,m1Revenue=s.arpu*s.m1RetentionPct/100,m2Revenue=s.arpu*s.m2RetentionPct/100,ltv90=s.arpu+m1Revenue+m2Revenue;return {trials,paid,cpc,cpi,cpt,cac,total,m1Revenue,m2Revenue,ltv90,adPayback:cac/s.arpu,fullPayback:total/s.arpu,adRetainedPayback:retainedPayback(cac,s),fullRetainedPayback:retainedPayback(total,s)}}
function renderScenario(){scenarioFields.forEach(([key,label])=>{const input=document.querySelector(`[data-scenario="${key}"]`);if(input&&document.activeElement!==input)input.value=scenario[key]});const m=scenarioMetrics();$('#scenarioResults').innerHTML=[['Projected trials',fmt(m.trials),'Installs × install-to-trial'],['Projected subscribers',fmt(m.paid),'Trials × trial-to-paid'],['Cost per click',money(m.cpc),'Spend ÷ clicks'],['Cost per install',money(m.cpi),'Spend ÷ installs'],['Cost per trial',money(m.cpt),'Spend ÷ trials'],['Subscriber CAC',money(m.cac),'Spend ÷ subscribers'],['M1 revenue / acquired sub',money(m.m1Revenue),'ARPU × M1 retention'],['M2 revenue / acquired sub',money(m.m2Revenue),'ARPU × M2 retention'],['90-day retained revenue',money(m.ltv90),'ARPU × (1 + M1 + M2)'],['Ad payback · full retention',paybackFmt(m.adPayback),'CAC ÷ monthly ARPU'],['Ad payback · retention-adjusted',m.adRetainedPayback,'Uses M1 and M2 expected revenue'],['Fully loaded · retention-adjusted',m.fullRetainedPayback,'CAC + LLM against retained revenue']].map(x=>`<div class="scenario-result"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');$('#scenarioSummary').innerHTML=`At the entered assumptions, <strong>${fmt(m.paid)} subscribers</strong> are acquired at <strong>${money(m.cac)} CAC</strong>. Ad-only payback is <strong>${m.adRetainedPayback}</strong> after applying ${scenario.m1RetentionPct}% M1 and ${scenario.m2RetentionPct}% M2 retention; fully loaded payback is <strong>${m.fullRetainedPayback}</strong>.<span class="scenario-formula">All outputs are formula-linked: spend → CPC/CPI/CPT/CAC; funnel rates → trials/subscribers; ARPU + retention → retained revenue/payback; LLM cost → fully loaded payback.</span>`;localStorage.setItem('hiastro-scenario',JSON.stringify(scenario))}
function loadScenarioFrom(d){scenario={...scenario,spend:+d.cost.toFixed(2),clicks:Math.round(d.cost/4.98115422),installs:d.installs,installTrialPct:+(d.trials/d.installs*100).toFixed(2),trialPaidPct:+(d.paid/d.trials*100).toFixed(2)};renderScenario()}
function render(selected='all'){
  const d=selected==='all'?totals():data.find(x=>x.date===selected);
  $('#periodText').textContent=selected==='all'?'14 fully matured daily cohorts · 22 Jun–5 Jul 2026 · paid outcome observed for 7 days':new Date(d.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})+' cohort · paid outcome observed for 7 days';
  $('#metrics').innerHTML=[metric(money(d.cost),selected==='all'?'Acquisition spend':'Singular spend'),metric(fmt(d.installs),'Installs'),metric(fmt(d.logins),'Subscription-mode logins'),metric(fmt(d.trials),'Trial starts'),metric(fmt(d.paid),'Paid subscribers'),metric(pct(d.loginTrial),'Login → trial'),metric(pct(d.trialPaid),'Trial → paid'),metric(money(d.cac),'Subscriber CAC',true)].join('');
  const july3=selected==='2026-07-03'; $('#chatCount').textContent=july3?'3,611':'—'; $('#chatRate').textContent=july3?'84.2% of subscription-mode logins':'Not verified for this cohort'; $('#paywallCount').textContent=july3?'3,110':'—'; $('#paywallRate').textContent=july3?'72.5% of subscription-mode logins':'Not verified for this cohort'; $('#activationNote').textContent=july3?'Verified July 3 Mixpanel funnel values.':'Select 3 July to view the verified checkpoint. Mixpanel tracking is incomplete on part of this 14-day period.';
  document.querySelectorAll('tbody tr').forEach(r=>r.classList.toggle('selected',r.dataset.date===selected)); renderScorecard(d); renderSummary(d,selected);
}
function lineChart(){const w=650,h=270,p={l:48,r:15,t:12,b:38},iw=w-p.l-p.r,ih=h-p.t-p.b,max=.25;const x=i=>p.l+i*iw/(data.length-1),y=v=>p.t+ih-v/max*ih;let s=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Daily conversion chart">`;for(let i=0;i<=5;i++){const v=i*.05,yy=y(v);s+=`<line x1="${p.l}" y1="${yy}" x2="${w-p.r}" y2="${yy}" stroke="#e5e8ec"/><text x="${p.l-9}" y="${yy+4}" text-anchor="end" font-size="10" fill="#6b7178">${Math.round(v*100)}%</text>`}const series=[['trialPaid','#111'],['loginTrial','#3d8dff'],['loginPaid','#61c5ed']];for(const [k,c] of series){s+=`<polyline fill="none" stroke="${c}" stroke-width="3" points="${data.map((d,i)=>`${x(i)},${y(d[k])}`).join(' ')}"/>`;s+=data.map((d,i)=>`<circle cx="${x(i)}" cy="${y(d[k])}" r="3" fill="${c}"/>`).join('')}data.forEach((d,i)=>{s+=`<text x="${x(i)}" y="${h-12}" text-anchor="middle" font-size="9" fill="#666">${i===0?'22 Jun':d.date.slice(8)}</text>`});return s+'</svg>'}
function barChart(){const w=650,h=270,p={l:50,r:15,t:12,b:38},iw=w-p.l-p.r,ih=h-p.t-p.b,max=1500,bw=iw/data.length*.64;let s=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Daily subscriber CAC chart">`;for(const v of [0,500,1000,1500]){const yy=p.t+ih-v/max*ih;s+=`<line x1="${p.l}" y1="${yy}" x2="${w-p.r}" y2="${yy}" stroke="#e5e8ec"/><text x="${p.l-9}" y="${yy+4}" text-anchor="end" font-size="10" fill="#6b7178">${v===0?'0':v/1000+'k'}</text>`}data.forEach((d,i)=>{const x=p.l+(i+.5)*iw/data.length-bw/2,y=p.t+ih-d.cac/max*ih;s+=`<rect x="${x}" y="${y}" width="${bw}" height="${p.t+ih-y}" fill="#3d8dff"/><text x="${x+bw/2}" y="${h-12}" text-anchor="middle" font-size="9" fill="#666">${i===0?'22 Jun':d.date.slice(8)}</text>`});return s+'</svg>'}
function init(){const sel=$('#dateSelect');sel.innerHTML='<option value="all">14-day overview</option>'+data.map(d=>`<option value="${d.date}">${new Date(d.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</option>`).join('');sel.addEventListener('change',()=>render(sel.value));$('#conversionChart').innerHTML=lineChart();$('#cacChart').innerHTML=barChart();$('#scenarioInputs').innerHTML=scenarioFields.map(([key,label])=>`<div class="scenario-field"><label for="scenario-${key}">${label}</label><input id="scenario-${key}" data-scenario="${key}" type="number" step="any" value="${scenario[key]}"></div>`).join('');document.querySelectorAll('[data-scenario]').forEach(input=>input.addEventListener('input',()=>{scenario[input.dataset.scenario]=Number(input.value)||0;renderScenario()}));$('#loadCohort').onclick=()=>loadScenarioFrom(sel.value==='all'?totals():data.find(d=>d.date===sel.value));$('#resetScenario').onclick=()=>{scenario={...scenarioDefaults};renderScenario()};$('#dataRows').innerHTML=data.map(d=>`<tr data-date="${d.date}"><td>${new Date(d.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</td><td>${money(d.cost)}</td><td>${fmt(d.installs)}</td><td>${fmt(d.logins)}</td><td>${fmt(d.trials)}</td><td><b>${fmt(d.paid)}</b></td><td>${d.p199}</td><td>${d.p299}</td><td>${d.p499}</td><td>${pct(d.loginTrial)}</td><td>${pct(d.trialPaid)}</td><td>${money(d.cac)}</td></tr>`).join('');document.querySelectorAll('tbody tr').forEach(r=>r.onclick=()=>{sel.value=r.dataset.date;render(r.dataset.date);scrollTo({top:0,behavior:'smooth'})});sel.value='2026-07-05';render(sel.value);renderScenario()}
function unlock(){sessionStorage.setItem('hiastro-access','yes');$('#lock').classList.add('hidden');$('#app').classList.remove('hidden')}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();if($('#password').value==='3011196420')unlock();else{$('#error').textContent='Incorrect access code';$('#password').select()}});$('#logout').onclick=()=>{sessionStorage.removeItem('hiastro-access');location.reload()};if(sessionStorage.getItem('hiastro-access')==='yes')unlock();init();
